### ISSUE TITLE
some NAs in miRScore_results

### ISSUE THREAD

**Issue by joweihsieh** [Aez35/miRScore#28]
Hi Allison,

I was trying to use miRScore for my de novo miRNA annotation in wheat, but I encountered some unexpected results in the output file (miRScore_results). Some of the miRNAs contained lots of "NA", including missing precursor information, even though I included it in my input files. Please find the attached image for reference.

Do you have any idea why this might be happening?

Thank you!
Jo-Wei

![Screenshot 2024-07-23 at 3 04 05 PM](https://github.com/user-attachments/assets/88e80778-ab41-4f07-80c0-2142a7a6e240)

**Comment by Aez35** [comment]
Hi Jo-Wei,

This issue was due to a misspelling of the flag, causing it to not report the precursor information. Thank you for catching that. As for the other NA's, if the miRNA sequence cannot be found within the hairpin, no other information besides what you provide can be reported. This has been resolved as of commit [8b20a6c](https://github.com/Aez35/miRScore/commit/8b20a6c0ea6f2339c1e6b58bc248c3f587822021)

Best,
Allison

**Comment by joweihsieh** [comment]
Hi Allison,

After rerunning the data using the latest version of miRScore and reviewing the results, I have some questions related to the output.

In the output file of miRScore_results, the flags of some miRNAs show "No mature or star reads detected," which seems to be due to zero values in either mReads or msReads. This seems odd because I can find those mature/star sequences in my libraries. Additionally, why isn't the number of totReads equal to the sum of mReads and msReads? I wonder if I misunderstood the explanation in the README. Could you please take a look and clarify this for me?

<img width="1456" alt="Screenshot 2024-07-27 at 12 53 44 PM" src="https://github.com/user-attachments/assets/8019a803-69a9-4f97-8d0a-e1faa9f4d064">


Thank you!
Jo-Wei

**Comment by Aez35** [comment]
Hi Jo-Wei,

To clarify the README, **totReads** is the total number of reads mapped to the hairpin precursor, not the total number of miR/miR* reads. This is an important distinction, because one criterion of a bona fide miRNA is at least 75% of all reads that map to the precursor must map to the miR/miR* duplex. **totReads** is reported to the user to allow them to verify this precision ((miR+miR*)/totReads). There are many cases where we see reads map all across the hairpin and not just at the miRNA duplex. This can be due to degraded RNA, other RNA species, etc. 

**mReads** and **msReads** reports the reads that map to the reported miR/miR* loci +/- 1 position. This variance is included to allow for imprecision in Dicer/DCL processing during biogenesis. It is required that at least 1 read map to both the miR and the miR* in order to be considered a high confidence miRNA. 

The first thing I suggest is to look at the 'Reads.csv' file in your output. This will give you an idea of how many reads are present for each locus in each of your libraries. If you are manually inspecting your libraries and seeing reads at these  locations, please let me know. Here is an example of how you might check this using the command miRScore uses:

```
# This example it set up for tae-MIR2275b. The start (9/64) and stop (31/87) index is +/- 1 to allow for that variance.
# Adjust BAM to the name of your library/libraries.

#miR
samtools view  -F 16 -e 'pos>= 9 && endpos<=31' alignments/BAM tae-MIR2275b | wc -l
#miR*
samtools view  -F 16 -e 'pos>= 64 && endpos<=87' alignments/BAM tae-MIR2275b | wc -l
```

When counting reads, I suggest avoiding the merged bam file. miRScore scores reads on an individual library basis to prevent false positive confirmation of a very sparse loci (i.e. 100 libraries with 1 read each). Therefore, if your merged bam shows you have 10 miR and 8 miR* reads, but the miRNA fails for not having reads at both positions, those reads likely stem from different libraries. Please let me know if you need further clarification or assistance.

Allison
